### ISSUE TITLE
[Question] provide file to open during test

### ISSUE THREAD

**Issue by mangkoran** [rhysd/vim-startuptime#5]
Is it possible to provide a file to open in the test? I have tried like `vim-startuptime -vimpath "vim /home/mangkoran/foo.html"` but it doesn't work.

**Comment by rhysd** [comment]
Give file paths after `--`:

```sh
vim-startuptime -- path/to/file
```

Arguments after `--` are passed to Vim process as command arguments.

**Comment by mangkoran** [comment]
Thank you very much it works! I forgot the file path is actually an argument 😅
